# MoveIt uses this configuration for controller management

trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01
  trajectory_duration_monitoring: true

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - iiwa_arm_controller
    - iiwa_hand_controller

  iiwa_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - iiwa_joint1
      - iiwa_joint2
      - iiwa_joint3
      - iiwa_joint4
      - iiwa_joint5
      - iiwa_joint6
      - iiwa_joint7
    action_ns: follow_joint_trajectory
    default: true
  hand_controller:
    type: GripperCommand
    joints:
      - iiwa_finger_joint1
    action_ns: gripper_cmd
    default: true
